// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLogs() {
  return window['go']['main']['NpcDeskApp']['ClearLogs']();
}

export function GetCommonSettings() {
  return window['go']['main']['NpcDeskApp']['GetCommonSettings']();
}

export function GetConfigContent() {
  return window['go']['main']['NpcDeskApp']['GetConfigContent']();
}

export function GetConfigDocument() {
  return window['go']['main']['NpcDeskApp']['GetConfigDocument']();
}

export function GetConfigPath() {
  return window['go']['main']['NpcDeskApp']['GetConfigPath']();
}

export function GetLogs() {
  return window['go']['main']['NpcDeskApp']['GetLogs']();
}

export function GetStatus() {
  return window['go']['main']['NpcDeskApp']['GetStatus']();
}

export function OpenConfigFolder() {
  return window['go']['main']['NpcDeskApp']['OpenConfigFolder']();
}

export function PickConfigFile() {
  return window['go']['main']['NpcDeskApp']['PickConfigFile']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['NpcDeskApp']['SaveConfig'](arg1);
}

export function SaveConfigDocument(arg1) {
  return window['go']['main']['NpcDeskApp']['SaveConfigDocument'](arg1);
}

export function StartClient() {
  return window['go']['main']['NpcDeskApp']['StartClient']();
}

export function StopClient() {
  return window['go']['main']['NpcDeskApp']['StopClient']();
}

export function ValidateConfigDocument(arg1) {
  return window['go']['main']['NpcDeskApp']['ValidateConfigDocument'](arg1);
}
