// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {npc} from '../models';
import {configdoc} from '../models';

export function ClearLogs():Promise<void>;

export function GetCommonSettings():Promise<npc.CommonSettings>;

export function GetConfigContent():Promise<string>;

export function GetConfigDocument():Promise<configdoc.Document>;

export function GetConfigPath():Promise<string>;

export function GetLogs():Promise<string>;

export function GetStatus():Promise<Record<string, any>>;

export function OpenConfigFolder():Promise<void>;

export function PickConfigFile():Promise<string>;

export function SaveConfig(arg1:string):Promise<void>;

export function SaveConfigDocument(arg1:configdoc.Document):Promise<void>;

export function StartClient():Promise<void>;

export function StopClient():Promise<void>;

export function ValidateConfigDocument(arg1:configdoc.Document):Promise<configdoc.Document>;
